name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --all-packages
          
      - name: Install Hatch
        run: uv pip install hatch

      - name: Format Check
        run: |
          hatch run fmt
        
      - name: Type Check
        run: hatch run types:check
        
      - name: Run Tests
        run: hatch run test:test-cov

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --all-packages
          
      - name: Install Hatch
        run: uv pip install hatch

      - name: Build docs
        run: hatch run docs:mkdocs build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  publish:
    needs: [lint, docs]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install build dependencies
        run: uv pip install build hatch

      - name: Build package
        run: uv build --all-packages

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
